#ifndef VIRTUAL_MACHINE_OPCODES_HPP
#define VIRTUAL_MACHINE_OPCODES_HPP

enum Opcodes {
    STORE_GLOBAL_OBJECT,
    STORE_OBJECT_FUNCTION,
    DEFINE_OBJECT_FUNCTION,
    LOAD_GLOBAL_OBJECT,

    STORE_GLOBAL_FUNCTION,

    STORE_GLOBAL_VARIABLE,
    LOAD_GLOBAL_VARIABLE,
    STORE_VARIABLE,
    LOAD_VARIABLE,

    LOAD_STRING,
    ADD_STRING,
    EQUAL_STRING,
    NOT_EQUAL_STRING,
    PEEK_STRING,
    PRINT_STRING,

    LOAD_NUMBER,
    ADD_NUMBER,
    MULTIPLY_NUMBER,
    DIVIDE_NUMBER,
    SUBTRACT_NUMBER,
    MOD_NUMBER,
    EQUAL_NUMBER,
    GREATER_THAN_NUMBER,
    GREATER_THAN_EQUAL_NUMBER,
    PRINT_NUMBER,

    LOAD_BOOLEAN,
    EQUAL_BOOLEAN,
    PEEK_BOOLEAN,
    PRINT_BOOLEAN,

    LOAD_POINTER,
    PEEK_POINTER,
    FREE,

    CALL_FUNCTION,
    CALL_OBJECT_FUNCTION,
    LOAD_ARGUMENT,
    RETURN_EMPTY,
    RETURN,

    HALT,

    OPCODES_COUNT
};

#endif //VIRTUAL_MACHINE_OPCODES_HPP
